server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由id，建议配合服务名
          uri:  lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT #匹配路由名 8001 8002
          predicates:
            - Path=/payment/hystrix/get/**  # 断言，路径相匹配的进行路由
           # - Between=2020-11-16T23:49:43.341+08:00[Asia/Shanghai],2020-11-16T23:59:43.341+08:00[Asia/Shanghai]
           # - Query=username,\d+
            - Cookie=chen,aini
        #第二个路由
        - id: payment_route2 # 路由id，建议配合服务名
          uri:  lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT #匹配路由名 8001 8002
          predicates:
            - Path=/payment/hystrix/circuitBreaker/**  # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/