server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  ##<insert id="create" parameterType="Payment" Payment就会自动映射
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    #是否注册自己到EurekaServer
    register-with-eureka: true
    #是否抓取已有的注册信息  集群必须为ture-才能和ribbon配合使用
    fetchRegistry: true
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #修改eureka中注册的微服务的名称
    instance-id: payment8001
    #显示ip
    prefer-ip-address: true
    #设置心跳时间
    lease-renewal-interval-in-seconds: 1
    #eureka服务端受到最后一次心跳后等待是时间上线，超时就会剔除服务   默认是90S
    lease-expiration-duration-in-seconds: 2
